all:
	make -f Makefile
	mkdir -p image/usr/bin
	cp -p src/hexedit image/usr/bin
	arm-linux-androideabi-strip image/usr/bin/hexedit
	mkdir -p out
	tar cfz out/data.tar.gz -C image "." 
	tar cfz out/control.tar.gz ./control 
	echo "2.0" > out/debian-binary
	rm -f hexedit_0.9.3_kbox.deb
	ar rcs hexedit_0.9.3_kbox.deb out/debian-binary out/data.tar.gz out/control.tar.gz 
	cp hexedit_0.9.3_kbox.deb ../../out

clean:
	make -f Makefile clean
	rm -rf image/
	rm -rf out/
	rm -f *.deb
